import type { Metadata } from 'next'
import './globals.css'
import Header from './Header'
import { geistMono, geistSans } from './fonts'
import 'animate.css/animate.min.css'
//import LoadingBar from './LoadingBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Acme',
    description: 'Acme is a...',
    type: 'website',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <Header />

          {/* Main content area */}
          <main className="flex-grow bg-off-white">
            <div className="container">{children}</div>
          </main>

          {/* Footer */}
          <footer className="bg-gray-800 text-white py-4">
            <div className="container mx-auto px-4">
              <p>Footer Content</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  )
}
