import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from './Header'

import 'animate.css/animate.min.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: 'Acme',
    description: 'Acme is a...',
type: 'website'  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    <div className="flex flex-col min-h-screen">
      {/* Header */}
      {/* <header className="animate__animated animate__slideInDown fixed top-0 left-0 right-0 z-50 py-4 shadow-md bg-[rgba(57,66,69,0.8)] border-t-[rgba(37,42,44,0.5)] z-[22] w-full left-0 border-b border-b-[rgba(0,0,0,0.07)] text-[#cacaca]">
        <div className="container mx-auto px-4">
          <h1 className="text-2xl">Floating Header</h1>
        </div>
      </header> */}
      <Header />

      {/* Main content area */}
      <main className="flex-grow bg-off-white">
        <div className="container">
          {children}
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-4">
        <div className="container mx-auto px-4">
          <p>Footer Content</p>
        </div>
      </footer>
    </div>
      </body>
    </html>
  );
}
